### ISSUE TITLE
What is your experimental environment

### ISSUE THREAD

**Issue by connorchen** [ShayanPersonal/Kaggle-Passenger-Screening-Challenge-Solution#1]
my environment:
gtx1060 6G
memory 16G
but it throw an error : out of memory (OOM)
so what is your experimental environment
please

**Comment by ShayanPersonal** [comment]
Hi connorchen,

I used a GTX 1080 ti with 11 GB of VRAM and 32 GB of system RAM. You might be able to train with the GTX 1060 if you decrease the batch size, but 16 GB of system RAM may not be enough to load in the dataset from Kaggle. 

You might be able to get around this by adding swap space through your operating system, or modifying the dataloader to take in filenames and only load in one batch of data into memory at a time.

**Comment by connorchen** [comment]
Thank you for your reply @ShayanPersonal ,
So system ram is not a big problem now
But the memory of the video card is definitely not enough
I'm going to cascade two gtx1060
I hope I can succeed
Thanks again
